### ISSUE TITLE
Want to run the project

### ISSUE THREAD

**Issue by douglasdcm** [shahriar-rahman/Web-Scraping-Audible-Using-Selenium-Webdriver#1]
Hi, how are you? What is the version of Python you are using? How do I run the crawler? Thank you!

**Comment by shahriar-rahman** [comment]
Hey, my apology for the late response. This project was done using Python 3.11. I used the PyCharm IDE (2023.1) to run the crawler script, unlike a Scrapy crawler, where you need to use PowerShell to initiate a crawling procedure. Hope this helps, and let me know if any issues arise.

**Comment by douglasdcm** [comment]
Hi, thank you! I use Linux and VSCode. What is the command you use in PowerShell? I'll try to adapt it to Linux.

**Comment by shahriar-rahman** [comment]
In Windows, I use “cd Scrapy-Project” to select the project directory, then I write “scrapy crawl Spider_Name” to run the script, where ‘Spider_Name’ is the name of the bot I initialized inside my spider script (which is located in the ‘spiders’ folder in the project directory). 

The hierarchy goes as follows:
Project-Name > Project-Name > spiders > spider_script.py

In a few days, I am also planning to reorganize all my Scrapy projects and project files and edit the Readme so that it would be easier for everyone to understand the process more clearly as it can often be quite complex. Feel free to point out any flaws and/or confusion.

**Comment by douglasdcm** [comment]
I could run it in Linux, thank you!
